Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStok.Models.Entity;
namespace MVCStok.Controllers
{
    
    public class SaleController : Controller
    {
        // GET: Sale
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Sales()
        {
            var saleee =db.tbl_satislar.ToList();
            return View(saleee);
        }

        

        [HttpGet]
        public ActionResult new_sales()
        {
            return View();
        }


        [HttpPost]
        public ActionResult new_sales(tbl_satislar p)
        {
            db.tbl_satislar.Add(p);
            db.SaveChanges();
            return RedirectToAction("Sales");
        }

        public ActionResult delete(int id)
        {
            var saleee = db.tbl_satislar.Find(id);
            db.tbl_satislar.Remove(saleee);
            db.SaveChanges();
            return RedirectToAction("Sales");
        }

        public ActionResult sale_guncelle(int id)
        {
            var saleee = db.tbl_satislar.Find(id);
            return View("sale_guncelle", saleee);
        }

        public ActionResult Guncelle (tbl_satislar p1)
        {
            var saleee = db.tbl_satislar.Find(p1.SatisID);
            saleee.Urun = p1.Urun;
            saleee.Musteri = p1.Musteri;
            saleee.Adet = p1.Adet;
            saleee.Fiyat = p1.Fiyat;
            db.SaveChanges();
            return RedirectToAction("Sales");
        }

    }
}

Views/Sale/Sales.cshtml
@using MVCStok.Models.Entity
@model List<tbl_satislar>

@{
    ViewBag.Title = "Satışlar";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<h2>Satışlar</h2>

<table id="tbl1" class="table table-hover">
    <thead>
        <tr>
            <th>Satış ID</th>
            <th>Ürün ID</th>
            <th>Ürün Adı</th>
            <th>Müşteri Adı</th>
            <th>Müşteri Soyadı</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var sales in Model)
        {
            <tr>
                <td>@sales.SatisID</td>
                <td>@sales.Urun</td>
                <td>@sales.tbl_urunler.UrunAd</td>
                <td>@sales.tbl_musteriler.MusteriAd</td>
                <td>@sales.tbl_musteriler.MusteriSoyad</td>
                <td>@sales.Adet</td>
                <td>@sales.Fiyat</td>
                <td>@Html.ActionLink("Sil", "delete", new { id = sales.SatisID }, new { @class = "btn btn-danger", onclick = "return confirm('Gerçekten Silmek İstiyormusunuz?')" })</td>
                <td><a href="/Sale/sale_guncelle/@sales.SatisID" class="btn btn-warning">Güncelle</a></td>
            </tr>
    
    }
        </tbody>
    </table>
    <a href="/Sale/new_sales/" class="btn btn-success">Yeni Sipariş Ekle</a>
    <script type="text/javascript" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script>
        $('#tbl1').DataTable();
    </script>
    @* İsteğe bağlı olarak modal pop-up kullanılabilir.Aşağıdakiler modal pop-up kodlarıdır. <button class="btn btn-primary" type="button" data-toggle="modal" data-target="#Modal1">
            Satış Yap
        </button>
        <div class="modal" id="Modal1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Satış Yapma Ekranı</h2>
                    </div>
                    <form method="post" action="/Sale/new_sales">
                        <div class="modal-body">
                            <label>Ürün ID</label>
                            @Html.TextBoxFor(m => m.Urun, new { @class = "form-control" })
                            <br />
                            <label>Müşteri ID</label>
                            @Html.TextBoxFor(m => m.Musteri, new { @class = "form-control" })
                            <br />
                            <label>Adet</label>
                            @Html.TextBoxFor(m => m.Adet, new { @class = "form-control" })
                            <br />
                            <label>Fiyat</label>
                            @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
                            <br />
                            <button type="submit" class="btn btn-success">Satış Yap</button>
                            <button type="submit" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>*@

Views/Sale/new_sales.cshtml
@{
    ViewBag.Title = "new_sales";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Ürün ID</label>
        <input type="text" class="form-control" name="Urun" required="" />
    </div>
    <div>
        <label>Müşteri ID</label>
        <input type="text" class="form-control" name="Musteri" required="" />
    </div>
    <div>
        <label>Adet</label>
        <input type="text" class="form-control" name="Adet" />
    </div>
    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="Fiyat" />
    </div>
    <div style="margin-top:15px"><button class="btn btn-success">Satış Yap</button></div>

</form>

Views/Sale/sale_guncelle.cshtml
@model MVCStok.Models.Entity.tbl_satislar
@{
    ViewBag.Title = "sale_guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Guncelle", "Sale", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.SatisID)
    @Html.TextBoxFor(m => m.SatisID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Urun)
    @Html.TextBoxFor(m => m.Urun, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Musteri)
    @Html.TextBoxFor(m => m.Musteri, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Adet)
    @Html.TextBoxFor(m => m.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.Fiyat)
    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
</div>
    <div>
        <button class="btn btn-primary">Satış Güncelle</button>
    </div>
}